### ISSUE TITLE
Error: Cannot find module 'date-fns/format'

### ISSUE THREAD

**Issue by hellos3b** [airtoxin/purify-ts-extra-codec#4]
I added this library to my project for the stringified type, and it looks like a development build or something that relies on `date-fns` is trying to be imported, which I don't have in my project

```
$ ts-node src/index.ts
Error: Cannot find module 'date-fns/format'
Require stack:
- work_dir/node_modules/purify-ts-extra-codec/dist/purify-ts-extra-codec.cjs.development.js
- work_dir/node_modules/purify-ts-extra-codec/dist/index.js
- work_dir/path/to/index.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (work_dir/node_modules/purify-ts-extra-codec/dist/purify-ts-extra-codec.cjs.development.js:8:34)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
```

I'm using `ts-node` inside a yarn project

node: v12.13.1
npm: 6.12.1
yarn: 1.3.2

**Comment by airtoxin** [comment]
@hellos3b Thank you for your report.
`date-fns` required in Date Codec as a peerDependency if use that.
But if you did not use Date Codec in your project, this is bug of this library.

**Comment by hellos3b** [comment]
No problem! And yup, I did not import the Date codec

**Comment by airtoxin** [comment]
@hellos3b Try to use version 0.3.2!

```
$ npm info purify-ts-extra-codec

purify-ts-extra-codec@0.3.2 | MIT | deps: 1 | versions: 7
Extra utility codecs for [purify-ts](https://gigobyte.github.io/purify/).
https://github.com/airtoxin/purify-ts-extra-codec#readme

dist
.tarball: https://registry.npmjs.org/purify-ts-extra-codec/-/purify-ts-extra-codec-0.3.2.tgz
.shasum: 2c4e40faadb5f88a44c5f0f8184b4bac78a35af6
.integrity: sha512-0PpMbcJcqkjnEnHNrgrqvuifmlHWvtO+VoSx9wqBZkuTN9AvFz9kPC5OOsGl4Y+kIgdY3s4IsD+4k4D9yNGXDA==
.unpackedSize: 110.9 kB

dependencies:
date-fns: ^2.14.0 

maintainers:
- airtoxin <airtoxin@icloud.com>

dist-tags:
latest: 0.3.2  

published 32 seconds ago by airtoxin <airtoxin@icloud.com>
```
